import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Universe } from "./components/Universe";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <Universe>
          <main>{children}</main>
        </Universe>
      </body>
    </html>
  );
}
